### ISSUE TITLE
Вернуть ввод времени в планшетное приложение

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#101]
Предложение от А.Тониса:

> khalexxx
команда №488, Пикник на обочине, Левченко Дмитрий.
У него стоит неявка на смену карт. Димо пока в командировке. Он, подозреваю, вообще не отслеживает обсуждения по ММБ сейчас.
Может там где-то есть в бэкапах сведения о его карточке первого этапа?

>valechka
нашла, поправила, почему то не случилась отметка на сканере
Ответить Развернуть Новый комментарий

> atonis
Вот. Именно поэтому надо вернуть в планшетное приложение отображение, а лучше и ввод времени.

**Comment by yuriyweiss** [comment]
В приложение возвращена опция редактирования времени.
Доступность редактирования можно отключить в настройках, чтобы неопытные операторы не поменяли что-то ошибочно.
Можно как редактировать существующую запись со сканера, так и создавать новую, но тогда у неё будет logger_id = -1.
