### ISSUE TITLE
Учитывать время старта по первой отметке на сканере

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#102]
Предложение:

Sedov D. E (MIEE) через googlegroups.com:
 Это ещё хорошо участники не в курсе что можно 2 раз отсканироваться, и 2 время как я понял пойдет в зачет, а не первое, когда карту выдали.

**Comment by yuriyweiss** [comment]
Мы обдумывали, какое время учитывать.
Если участник случайно отсканировался сначала, а реально стартует потом, то мы его беспричинно оштрафуем на этот зазор.

**Comment by azotov** [comment]
Согласен с Юрой.
Но при этом я бы предложил выводить на планшете список команд, которые на старте отсканировались два раза, а на карточках команд, которые ошибочно отсканировались сначала, при повторном сканировании, которое произошло по уважительной причине, ставить пометки маркером. Таким образом мы отследим те команды, которые скрытно зашли второй раз на пункт сканирования.

**Comment by Pavel-Y** [comment]
А участнику дают карту сразу после первого сканирования?

С другой стороны, вон, на Московском марафоне тоже автоматическая отметка старта "по готовности" (там стартует несколько тысяч, старт растянут минут на 10-15).  Если я остановился завязать шнурки до стартовых ворот, все ОК. Если сразу после - сам виноват, время уже пошло.

Ответ azotov'y: ок, хотя бы список таких команд отслеживать.

**Comment by Pavel-Y** [comment]
Обсуждали на встрече. У Андрея записано, что решили. НЯП, "старт по последней отметке, финиш по первой", но надо уточнить

**Comment by yuriyweiss** [comment]
Приняли в итоге вариант:
Старт фиксируется по первой отсечке, финиш - по последней.
