### ISSUE TITLE
Дать возможность сливать с логгера данные со всех точек сразу

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#105]
Валентина Петроченко предложила:
"возможно  чтобы  сливались  с логера [на планшет] все данные со всех точек сразу,  тогда не придется перебирать все точки".

**Comment by Pavel-Y** [comment]
Статус: заморожено. На встрече было обсуждение, чем кончилось, не помню.

**Comment by jekyll2014** [comment]
Решили, что надо это сделать.

**Comment by yuriyweiss** [comment]
Готово.
