### ISSUE TITLE
Старт команды после окончания старта

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#106]
При старте команды после окончания стартового интервала автоматически ставить время старта, равное последней минуте стартового интервала.

Говорят, весной 2015 с этим были проблемы и пришлось что-то делать вручную.

**Comment by yuriyweiss** [comment]
Принято к исполнению, но пока не приступал.

**Comment by Pavel-Y** [comment]
Полное описание, что решили на встрече - у Андрея Калугина. НЯП, это решили делать, и именно в такой формулировке. 
Андрей?

**Comment by jekyll2014** [comment]
Да, был такой разговор и решили автоматом опоздавшим проставлять время
окончания старта вместо реального времени со сканера.

**Comment by yuriyweiss** [comment]
Готово.
