### ISSUE TITLE
На главной странице в консоли FireBug видны ошибки file not found

### ISSUE THREAD

**Issue by se-ti** [realtim/mmb#107]
На главной странице в консоли FireBug видны ошибки: 
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb03/mmb03v-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb03o/mmb03o-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb04o/mmb04o-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb05/mmb05v-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb06/mmb06v-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb05o/mmb05o-logo.png"
"NetworkError: 404 Not Found - http://mmb.progressor.ru/mmb11o/mmb11o-logo.png%20%C2%A0%C2%A0%C2%A0"

**Comment by leonidfishkis** [comment]
Для ММБ до 2005 lite нет логотипов
для 2006 и позже нужно загрузить логотипы значков.
После этого нужно переписать код в index.php и убрать старые ссылки из Raids

**Comment by leonidfishkis** [comment]
Сейчас тоже видны?

**Comment by se-ti** [comment]
Сейчас не видны.

**Comment by leonidfishkis** [comment]
Спасибо!

**Comment by se-ti** [comment]
Однако все интереснее: 
Если кликнуть в колонке марш-бросок на старые броски (весна 2006 и раньше), или просто повыбирать их в селекте, то в ЛВУ будет пустое место и символ незагрузившейся картинки.

**Comment by leonidfishkis** [comment]
Для этих  ММБ эмблему ещё не рисовали.  Можно прозрачный гиф загрузить или
сделать файл, что "нет эмблемы"

23 июля 2015 г., 2:28 пользователь Serge Titov <notifications@github.com>
написал:
