### ISSUE TITLE
Настроить на сервере кеширование

### ISSUE THREAD

**Issue by se-ti** [realtim/mmb#113]
Сейчас на сервере ничего не кешируется.

В результате __любой__ переход по сайту приводит к загрузке 520 Кб логотипов.
Содержательных данных при этом может быть 10-20 Кб

**Comment by leonidfishkis** [comment]
Включил следующее в htaccess
<ifModule mod_headers.c>
	#кэшировать html, htm, pdf файлы на один день
	<FilesMatch "\.(html|htm|pdf)$">
		Header set Cache-Control "max-age=43200"
	</FilesMatch>
	#кэшировать css, javascript  на одну неделю
	<FilesMatch "\.(js|css)$">
		Header set Cache-Control "max-age=604800"
	</FilesMatch>
	#кэшировать флэш и изображения на месяц
	<FilesMatch "\.(flv|swf|ico|gif|jpg|jpeg|png)$">
		Header set Cache-Control "max-age=2592000"
	</FilesMatch>
	#отключить кэширование php и cgi
	<FilesMatch "\.(php|cgi)$">
		Header unset Cache-Control
	</FilesMatch>
</IfModule>

<ifModule mod_expires.c>
	ExpiresActive On
	#по умолчанию кеш в 3 секунды
	ExpiresDefault "access plus 3 seconds"
	#кэшировать флэш и изображения на месяц
	ExpiresByType image/x-icon "access plus 2592000 seconds"
	ExpiresByType image/jpeg "access plus 2592000 seconds"
	ExpiresByType image/png "access plus 2592000 seconds"
	ExpiresByType image/gif "access plus 2592000 seconds"
	ExpiresByType application/x-shockwave-flash "access plus 2592000 seconds"
	#кэшировать css, javascript на одну неделю
	ExpiresByType text/css "access plus 604800 seconds"
	ExpiresByType text/javascript "access plus 604800 seconds"
	ExpiresByType application/javascript "access plus 604800 seconds"
	ExpiresByType application/x-javascript "access plus 604800 seconds"
	#кэшировать html, htm, pdf файлы на один день
	ExpiresByType text/html "access plus 43200 seconds"
	ExpiresByType application/pdf "access plus 43200 seconds"
	#кэшировать xml файлы на десять минут
	ExpiresByType application/xhtml+xml "access plus 600 seconds"
</ifModule>
