### ISSUE TITLE
Хочется видеть ссылки на карты над результатами

### ISSUE THREAD

**Issue by se-ti** [realtim/mmb#114]
Старый вид гораздо удобнее, чем ссылка на склад с кучей лишнего.
В идеале там должны быть маленькие превью, как было сделано Славой, но в первом приближении подойдут и просто ссылки на листы карт.
Текущую ссылку на файлы можно оставить.

Вставлять полную картинку и ресайзить ее не надо -- будет очень долго грузиться.

Сравнить:
http://slazav.mccme.ru/mmb/res08b.htm
http://mmb.progressor.ru/php/mmbscripts_tit/index.php?files&RaidId=24
http://slazav.mccme.ru/mmb/08/p3b.jpg

P.S. Use case: я после ММБ хочу посмотреть, как лидеры проходили рогейны. Мне нужны 2 или 3 листа карты и список команд с пропущенными КП.

**Comment by leonidfishkis** [comment]
На мой взгляд, разным людям хочется видеть разное, поэтому я не уверен, что
нужны карты.
Кроме того, карты загружаются обычно позже, чем результаты.
Философские вопросы по интерфейсу лучше обсудить в группе
mmbsitedeveloper@gmail.com
26 июля 2015 г. 18:07 пользователь "Serge Titov" <notifications@github.com>
написал:
