### ISSUE TITLE
На страницах результатов не показывать бессмысленные фильтры

### ISSUE THREAD

**Issue by se-ti** [realtim/mmb#115]
Если дистанция только одна -- не показывать фильтр по дистанции.

В фильтре по точкам оставить только точки, по которым есть отметки.

**Comment by leonidfishkis** [comment]
Фильтр по точкам можно  доработать либо через потенциально возможные точки (там, где есть скан-точки), либо по загруженным данным.
Сначала проблуем второй вариант.
