### ISSUE TITLE
С осени 2012 г у команд исчезли рейтинговые очки

### ISSUE THREAD

**Issue by se-ti** [realtim/mmb#123]
На обеих тестовых базах.
Грузится по 70 сек, оч. долго :(

**Comment by leonidfishkis** [comment]
А что с этой задачей? Я правильно понимаю, что она уже реализована и нужно повесить "Для тестирования"

**Comment by se-ti** [comment]
Я занимался только ускорением.
С тем, откуда берется рейтинг, и почему он исчез, я не разбирался

**Comment by leonidfishkis** [comment]
Тогда поясни, что значить заголовок задачи? Рейтинг рассчитывается для
каждого пользователя. Пример, где он исчез можешь привести?



27 августа 2015 г., 23:57 пользователь Serge Titov <notifications@github.com

**Comment by se-ti** [comment]
У меня это выглядело, как рейтинг 13 у Марины Галкиной, вместо 17 на бою.
А если сказать "детализировать", то у всех ММБ, начиная с осени 12 года, места у команд есть, а рейтинг -- пустой.

Собственно вот: http://mmb.progressor.ru/php/mmbscripts_tit/?rating=all
1.5 недели назад эффект наблюдался на обеих тестовых машинах, сейчас только на моей.

Или надо что-то запустить, чтобы рейтинг пересчитался?

**Comment by leonidfishkis** [comment]
На рабочей я этого не наблюдаю
http://mmb.progressor.ru/php/mmbscripts/?rating=all
<http://mmb.progressor.ru/php/mmbscripts_tit/?rating=all>


>Или надо что-то запустить, чтобы рейтинг пересчитался?
Раньше была отдельная кнопка, но я её убрал и теперь рейтинг
пересчитывается вместе с результатами.
На рабочей не надо пересчитывать.  На твоей - можешь войти под
администратором  и запустить (Обмен данными - Пересчитать результаты)

>1.5 недели назад эффект наблюдался на обеих тестовых машинах, сейчас
только на моей.
так я на тестовую _git перезалил основную базу, чтобы тестирование по
регистрации проводить на реальных данных.

Мне кажется, что задачу можно закрывать.



28 августа 2015 г., 0:51 пользователь Serge Titov <notifications@github.com>
написал:

**Comment by se-ti** [comment]
Зашел в обмен данными, сказал пересчитать для нескольких МБ. Не помогло.
Все равно у Марины рейтинг 13, и ни у кого нет рейтинга после осени 12 года.

**Comment by leonidfishkis** [comment]
Да, нашёл ошибку - нужно вызов
RecalcTeamUsersRank($raidid);  внутри
RecalcTeamResultFromTeamLevelPoints($raidid, $teamid)
поставить ниже расчета результатов (следующий запрос)

Попробую завтра исправить.


28 августа 2015 г., 1:17 пользователь Serge Titov <notifications@github.com>
написал:
