### ISSUE TITLE
Работа с полем team_outofrange (команда вне зачета)

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#135]
1)Надо выяснить, какой код создает разные варианты признака команды в зачете (0 и NULL), и сделать все единообразно и в коде, и в базе. Для команды вне зачета остается значение 1.

2)Хорошо бы добавить новый вариант значения команды вне зачета - 2. Оно везде должно обрабатываться точно также, как 1, но текстовое сообщение для нее должно быть не "вне зачета", а "дисквалификация". Ну и этот вариант пусть могут ставить командам в базе только администраторы (в принципе пока интерфейс для ввода можно и не делать, дисквалификация случается редко и пока можно и вручную через phpmyadmin ее вводить).

**Comment by leonidfishkis** [comment]
На мой взгляд, это нужно ставить, не как атрибут команды, а не как особый
вид ошибки на точке.
Зачем сознательно обрезать информацию - так моно вписать комментарий в
нужной точке и поставить "ошибку" дисквалификация.
И не нужно будет нагружать поле _outofrange дополнительным смыслом.




2015-10-20 13:06 GMT+03:00 Alexander Zotov <notifications@github.com>:

**Comment by leonidfishkis** [comment]
Опечатался:
не как атрибут команды, а как особый вид ошибки на точке.

20 октября 2015 г., 14:01 пользователь Леонид Фишкис <
leonidfishkis@gmail.com> написал:

**Comment by leonidfishkis** [comment]
Да, и прежде, чем гроворить об ошибке я бы понаблюдал за Teams по итогам этого марш-броска.
Сейчас в базе я заменил все NULL на 0   посмотрим, возникнут ли новые NULL

**Comment by leonidfishkis** [comment]
Посмотрел - судя по данным ошибка в объединении команд

**Comment by leonidfishkis** [comment]
можно тестировать
