### ISSUE TITLE
Время ввода/редактирования результата команды на точке

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#142]
Это время хранится в поле TeamLevelPoints.teamlevelpoint_date. Но так как у этого поля стоял атрибут "on update CURRENT_TIMESTAMP", то содержимое этого поля обновлялось при любом редактировании записи, в том числе при пересчете результата команды на точке и поиске ошибок. В результате реальное время редактирования времени команды оказывалось затертым. Атрибут этот я убрал, но надо проверить корректность всей логики работы с полями teamlevelpoint_date, user_id и device_id. Правильная логика следующая:

При создании новой записи в таблице TeamLevelPoints при импорте с планшета в поле teamlevelpoint_date должно быть время ввода результата на планшете, в поле device_id - ID планшета, а в поле user_id - ID оператора планшета (обычно это владелец планшета).

При создании новой записи в таблице TeamLevelPoints через сайт в поле teamlevelpoint_date должно быть текущее время, в поле device_id - 1, в поле user_id - ID пользователя, который создал запись.

При редактировании существующей записи в таблице TeamLevelPoints через сайт поля teamlevelpoint_date, device_id и user_id должны изменяться ТОЛЬКО в том случае, если было изменено значение teamlevelpoint_datetime.  Значения этих полей меняются, соответственно, на текущее время, 1 и ID пользователя, который поменял время команды.

**Comment by leonidfishkis** [comment]
Это ещё актуально?

**Comment by azotov** [comment]
Частично актуально. В результате ввода электронной отметки предлагаю убрать из TeamLevelPoints и TeamLevelDismiss поле device_id (так как теперь нет понятия "результатов", поступивших с конкретного устройства"), а в user_id сохранять id пользователя, который отредактировал данные, и 0, если данные были автоматически импортированы скриптом импорта.

**Comment by leonidfishkis** [comment]
#335
