### ISSUE TITLE
Поле комментария на точке и у команды в целом

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#143]
Сейчас получилось так, что после перехода на мою функцию поиска ошибок поле комментария  у команды не обновляется просто после поиска ошибок и надо вызывать пересчет результатов. Я готов реализовать этот функционал, но хочу здесь сначала обговорить принципы работы с комментариями (чтобы убедиться, что я их понимаю правильно) + на одну ошибку в построении таблицы результатов.

Итак, поле комментария teamlevelpoint_comment может редактроваться только через сайт, его непустое значение не означает ошибку - это просто примечание оператора. Это поле не меняется при работе валидатора.

Поле комментария team_comment не может редактироваться через сайт и его содержимое целиком перегенерируется валидатором. В нем сначала перечисляются через запятую непустые комментарии teamlevelpoint_comment, потом после слова "Ошибка:" - текстовые расшифровки положительных значений error_id (по одному на каждый тип ошибки, обнаруженный на точках, посещенных данной командой), потом после слова "Предупреждение:" - текстовые расшифровки для отрицательных error_id.

И теперь про баг: на места команд в таблице результатов не должны влиять отрицательные error_id. Это не ошибки, а предупреждения. Результаты на точках с отрицательными error_id полностью корректные и их можно использовать для вычисления общего результата команды и ее места. Это признак именно подозрительных данных, на которые стоит обратить внимание оператору, но команду с такими данными не нужно "поражать в правах". Леня, этот момент к тебе.

**Comment by leonidfishkis** [comment]
Я внёс правки. 
Порядок в комментариях будет не совсем тот, что ты описал, но при желании можно легко изменить в  functions ,  RecalcTeamResultFromTeamLevelPoints

**Comment by leonidfishkis** [comment]
И ещё: после валидации сверху выводится сообщение "Проверка данных завершена, найдено ошибок: 1"  Сделай, пожалуйста, это сообщение в стандартную статусную строку, добавив к "Результаты марш-броска пересчитаны"

**Comment by leonidfishkis** [comment]
И ещё важный момент: мне не нравится, что в результате оператор может проставлять только комментарии и не может выставить ошибку.  Можно написать в комменатрии "Дисквалификация" , но это никак не повлияет на место команды.   Я предлагаю тебе подумать над разделением списка ошибок на те, что ставит валидатор (и перезаписывет при каждом анализе), и те, что может ставить оператор через web-интерфейс сайта.  Делать дополнительный флаг, как ты предлагал дисквалифкация на всю команду (тип 2 outofrange)  - неправильно - это огрубляет сведения, и мы теряем информацию, где именно команда была дисквалифиуирована. Правильно -  поставить дисквалификацию именно в точке, где она произошла. КОнечно, можно усложнить анализ, добавить ещё одно поле и свой справоник, который не трогает валидатор, и который может ставить администратор, но по-моему,  логичнее разделить ошибки в существующем справочнике errors.

**Comment by azotov** [comment]
Сообщение в статусную строку добавил (но не тестировал).
Против идеи дать возможность оператору ставить некоторые ошибки вручную (на конкретной точке) не возражаю. Но реализовать это можно только двумя способами - или завести отдельное поле, или считать определенные кода ошибок необнуляемыми валидатором. Второй вариант мне нравится. Как договоримся? Или отказаться от предупреждений и считать все отрицательные кода ошибок - ошибками, проставляемыми оператором. Или добавить колонку в таблицу errors с флагом operator, который указывает на то, какой это тип ошибки - проставляемый валидатором или проставляемый оператором?

**Comment by leonidfishkis** [comment]
>Или добавить колонку в таблицу errors с флагом operator, который указывает на то, какой это тип ошибки - проставляемый валидатором или проставляемый оператором?

Мне так больше нравится.

**Comment by leonidfishkis** [comment]
Я добавил поле error_manual  и поставил 1 для ошибки "Дисквалификация"
Соответственно, если я правильно понимаю, то тпереь твой валидатор должен сбрасывать все ошибки с  error_manual = 0 и не трогать те, которые error_manual = 1, а в интерфейсе,наоборот, оператор может проставить только ошибки с error_manual = 1
Сейчас я это править уже не буду.

**Comment by azotov** [comment]
Примерно так.
Давай я сделаю так, чтобы валидатор вообще не проверял команды, у которых уже стоит код ошибки с error_manual = 1, а ты сделаешь так, чтобы в интерфейсе оператор мог проставить только ошибки с error_manual = 1.
Ну и сделаем это не прямо сейчас, а ближе к началу ммб, как не очень срочную задачу.

**Comment by leonidfishkis** [comment]
Да, давай.  Только для ошибки 0 в  интерфейсе нужно будет исключение делать и давать возможнсоть оператору её поставить ,иначе он не сможет исправить ошибочно поставленную "Дисквалификацию", например.

**Comment by azotov** [comment]
Реализовал алгоритм, когда команды с ошибками типа "выставленные вручную" вообще не проверяются валидатором. Не забудь оставить оператору возможность ставить только ошибки с ручными типами и "отсутствие ошибок". Также посмотри на то, как показывается списке команд дисквалификация (я дисквалифицировал свою команду на тестовой базе в ммб весна-2016). Там уж очень много всего намешано, в том числе пустых строк. Я бы оставил "_название_точки_ - дисквалификация. _текст комментария_с_причиной_".

И еще обнаружилась возможная ошибка - когда ты через сайт редактируешь результат команды на точке, то надо бы обновлять teamlevelpoint_date (время создания записи/редактирования данных) на текущее время. Без этого не получается в данных исправить ошибку "Время редактирования данных меньше времени на точке".

**Comment by leonidfishkis** [comment]
>Не забудь оставить оператору возможность ставить только ошибки с ручными типами и >"отсутствие ошибок". 

Напиши, пожалуйста, Вале ситуацию для тестирования - я, кажется, это ещё весной доделал.

**Comment by leonidfishkis** [comment]
>Там уж очень много всего намешано, в том числе пустых строк. Я бы оставил "названиеточки_ - дисквалификация. текст комментарияспричиной".
не понял.  В списке команд выводится интегральный комментарий по всем точкам, так что названия точек туда не ставятся, а то будет ещё больше путаницы и мусора.  Подроьности (на какой точке) хорошо видны в карточке команды.
