### ISSUE TITLE
В таблице результатов не указано сколько команд вышло на старт

### ISSUE THREAD

**Issue by crosser** [realtim/mmb#144]
Feature request:
Пролистав таблицу результатов, можно увидеть последнее назначенное место, то есть сколько команд дошло до финиша. Но нет способа узнать сколько команд отметилось на старте. Было бы интересно иметь эту информацию. Было бы удобно иметь число заявившихся, число стартовавших, и число финишировавших команд в отдельной строке перед табличкой.

**Comment by leonidfishkis** [comment]
Теперьв фильтре по точкам выводится информация о количестве команд и участников, прошедших через этоу точку.
