### ISSUE TITLE
Закрыть потенциальную возможность создавать команды в ммб до 2012 года

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#149]
Нужно убрать из кода переменную $OldMmb, по крайней мере в тех местах, где она дает дополнительные права по изменению данных в базе для старых марш-бросков. На текущий момент все результаты старых ммб успешно импортированы в базу и работа со старыми марш-бросками ничем не должна отличаться от обычных марш-бросков, у которых истек срок подачи апелляций.

**Comment by leonidfishkis** [comment]
Последнее письмо в поддержку опровергает факт успешного импорта, да и  #178.  Впрочем, флаг всё равно не работает, так что чистку флага можно вести.

**Comment by leonidfishkis** [comment]
Сейчас любой марш-бросок (в том числе старый) перестает быть доступным для втавки команды (в том числе для администратора) после закрытия протокола, так что проблему закрываю. 
Перемнная $OldMmb, осталась в фнкции привелегии и проверке создания команды, но от жтих функций надо избавляться и переходить на новые (частично уже сделано) в rights.php
