### ISSUE TITLE
Показывать ссылку на слияние пользователей только при наличии запросов

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#151]
Показывать пользователю ссылку на страницу с запросами на его слияние с другими пользователями только тогда, когда такие запросы есть и пользователь их может отменить.

**Comment by leonidfishkis** [comment]
Посмотри, пожалуйста, видишь ли ты ссылку на объединение - это я тебя решил с собой "объединить"
Ещё  там может быть оширбка в самой функции, какие статусы учитывать, а какие нет. Сейчас я возвращаю только длоя ситуации"Запрос" и "Объединение подтверждено"

**Comment by azotov** [comment]
Да, вижу.
Может быть для "Объединение подтверждено" подтверждено показывать и не стоит. Объединенный пользователь в этот момент, как я понимаю, залогиниться уже не сможет, а объединявший и так знает, что он объединил и видеть до бесконечности эту ссылку ему наверно не очень интересно. Но на этом моменте я не настаиваю, текущая версия тоже сойдет.
