### ISSUE TITLE
Некорректное определение прав на редактирование команды

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#154]
1)Функция CanCreateTeam названа не совсем удачно - она не проверяет возможность создания команд в принципе (реально команды можно создавать всегда, пока марш-бросок не закрыт), а можно ли создать ту конкретную команду, данные которой только что ввели на странице создания новой команды. Поэтому при вызове этой функции не в момент записи новой команды в базу может приводить к некорректной работе (например, при просмотре пользователем чужой команды в зачете после окончания регистрации функция считает, что создание новой команды пользователю запрещено). Надо иметь две функции - CanCreateTeam и ValidateTeamCreation.

2)Функция CanEditTeam, вызванная обычным пользователем, фактически проверяет, не наступило ли 8 часов до начала ММБ, когда изменение команд в зачете запрещено. Именно она используется для проверки возможности правки всех данных команды, кроме добавления нового участника. Для последнего действия дополнительно проверяется CanCreateTeam, что не совсем корректно (см.пункт 1).

Должно быть так (для обычных пользователей, редактирующих свою команду):
Команды вне зачета всегда могут редактировать свои данные.
При редактировании команд в зачете должны проверяться два порога - закрытие регистрации и 8 часов до старта (то есть $RaidStage <=1 и $RaidStage <= 2). После первого порога должно запрещаться добавление новых участников и смена дистанции (так как уже ушли в печать карточки, напечатанные под конкретную дистанцию и с конкретным набором участников). После второго порога должно быть запрещено редактирование всего остального, чтобы не рассинхронизировать данные в базе и планшетах.

**Comment by leonidfishkis** [comment]
А зачем тыпоставил метку "для тестирования"?
Она ставится, когда выложен на тестовую исправленный код, а я не правил ещё.
Или ты уже внёс соответствующие исправления?

**Comment by azotov** [comment]
Ошибся. Исправления не вносил.
