### ISSUE TITLE
Не передается POST переменная для элемента с атрибутом disabled 

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#159]
При обработке переменных POST формы возникает предупреждение, что не найден соответствующий индекс в массиве.
На stackowerflow  предлагают ситуацию исправлять на странцие с помощью js, я сейчас сделал в одном месте просто hidden элемент с тем. же названием.
Может красивее написать функцию инициализации, которая при отсутствии данных в POST берёт их из текущих значений в таблице.

**Comment by azotov** [comment]
Я в любых обработчиках GET/POST запросов, которые меняют содержимое базы придерживался бы следующей логики:

Если запрос должен создать новую запись (или удалить существующую по набору признаков), то проверять на isset все переменные, которые должна передавать форма (или ссылка с параметрами). Если хотя бы один из них не определен, то считать, что произошла нештатная ситуация и в принципе отклонять запрос на создание/удаление.

Если запрос должен произвести редактирование данных, то нужно прочитать все текущее состояние данных в структуру $old (если их в базе не оказалось, то действовать по логике создания новой записи или же отказать в редактировании - зависит от запроса). И затем заполнить аналогичную структуру $new новыми вариантами данных. Если какая-то из изменяемых переменных не проходит проверку на isset, то считаем, что мы ее не меняем. Дальше проверяем все остальные переменные и ищем те, у которых старые и новые значения отличаются. Если таких не нашлось, то ничего не меняем (и возможно сообщаем пользователю, что менять нечего). Если нашлись изменения в данных, то по каждой из изменяемых переменных проверяем, имеет ли инициатор запроса право проводить такие изменения и корректны ли новые значения переменных. Если хотя бы одну переменную пытаются поменять с нарушением прав доступа или на некорректное значение, то отменяем весь запрос на редактирование целиком. Если все ок, то меняем в базе данные на новые.

**Comment by leonidfishkis** [comment]
Да, я тоже придерживался бы подобной логики.
