### ISSUE TITLE
Невозможно создать команду с названием "Название команды"

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#163]
Вот хочу я так называться, и всё тут. А система не дает: "Не указано название." Исправьте, пожалуйста.

**Comment by leonidfishkis** [comment]
Не все желания пользователей можно и нужно выполнять. "Название команды" - это placeholder
Вероятность, что кто-то не ввёл название (и защита от этого) выше, чем кто-то захотел так назвать команду.  При жедании Вы можете придумать, как обойти этот запрет, но не забудьте, что в планшеты тоже люди вбивают, и им Ваше  желание тоже жизнь усложнит:
Одно дело 
 -Название команды
- Крутые перцы
- Номер
-123

а другое дело 
-Название команды
-Название команды
-...?
Пожалейте волонётров!
