### ISSUE TITLE
Возможность администратору сделать рассылку по всем участникам ММБ

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#166]
Тема, Сообщение, Тип (1 - информационная, 2 - экстренная)
При типе 1 учитывается флаг в карточке пользователя, при типе 2 - рассылка идёт по всем заявившимся

**Comment by leonidfishkis** [comment]
У нас есть следующие ситуации, когда письма нужны или могут быть полезны:

0.  подтвердить адрес почты для идентификации
1. сообщить об изменениях в карточке пользователя
2. сообщить что-то всем пользователям зарегистрированным на сайте (например, что начинвется  регистрация)
3. сообщить всем участнику команды об изменениях в карточке команды
4. сообщить  что-то всем участникам марш-броска

(пользователь - тот, кто зарегистрировался на сайте. участник - пользователь, который вошёл в команду)

Есть деление   пользователь/участник и  действия вызванные пользователем/по инициативе организаторов..
Оранизаторам нужна экстренная рассылка по всем участникам, экстренной рассылки всем пользователям пока не видно, хотя может и она возникнуть.
Эти экстренные ситуации дожны обходить флаги, и об этом нужно напсиать либо на сайте при регистрации команды и пользователя, либо в положении. На мой взгляд, можно ограничиться сайтом, но может какую-то общцю фразу "Участник согласен предоставить оргнаизаторам доступ к персональным данным для их одбработки" или что-то в этом роде стоит вкак раз в Положение включить.

Остальные ситуации должны реагировать на флаги.
Соотвественно, напрашивается флаг "информирование пользователя" и "информирование участника"   - сейчас эти два флага слиты в один,  но по-хорошему должны разделяться.  Можно, конечно, флаг "информирование участника"   перенести в команду, но я не уверен, что это будет понятно, и точно это флаг будет сложнее заметить, чем в карточке учатника.

Нужен ли флаг(и) для 1 и 3 (изменения пользовтаеля и изменения участника) - я не понимаю.  Пока я настроен убрать  из интерфейса флаг, (который планировался, как фдаг для 1 и 3 в будущем, чтобы не путать пользователей неработающей пока возможностью.

**Comment by azotov** [comment]
Я бы не стали временно удалять флаги или вводить новые. Сейчас ИМХО есть исчерпывающее количество флагов - два: разрешение на получение писем от робота и разрешение на получение неэкстренных писем от организаторов. Этого вполне достаточно для описания всех 5 вариантов.

То, что запрет на получение писем от робота еще не реализован, это не критично - его поставили только 3 участника и врядли поставят еще до следующего ммб - основной вал захода в свои профили для регистрации команд уже прошел. Этим 3 участникам можно вручную написать письма с извинениями за то, что пока им еще будут приходить письма от роботов (тем более, что все 3 разрешили получение писем от оргов).

**Comment by leonidfishkis** [comment]
От роботов нужно перпеисывать фнукии рассылки, и только тогда можно будет реализовать запрет - когда я на это соберусь - неизвестно, поэтому флаг, на мой взгляд, лучше и убрать. 
Если второй флаг не править, то точно текст пояснения переписать до официального опубликования, что такой флаг есть - там ерунда получилась.

**Comment by leonidfishkis** [comment]
В самом начале рассылки сдеалть дополнительно письмо в группу разработчки в стиле  "на сайте запущена рассылка"
