### ISSUE TITLE
более строгий фильтр на ссылки на впечатления пользователей

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#169]
1)в форме для ввода ссылки на впечатления выводится перечень всех-всех марш-бросков в базе, а надо показывать только те, на которые открылся старт.

2)При создании нового впечатления надо в полях "Адрес ссылки"  и "Название" запрещать использование значений по умолчанию ("Адрес ссылки" и т.д.)

3)Для ссылок типа 1-4 надо проверять на наличие http в начале ссылки.

4)Не должно быть дублирующихся записей с одинаковыми userlink_url для ссылок типа 1-4 и userlink_hide=0 (независимо от того, кто автор впечатления) и не должно быть двух записей типа 6 с userlink_hide=0 у пары user_id+raid_id.

**Comment by azotov** [comment]
И еще добавлю - позволить модераторам вводить вес рюкзака. В принципе оно заслуживает отдельной задачи как пожелание, но возможно будет проще разом внести в обработку впечатлений все эти моменты.

**Comment by leonidfishkis** [comment]
Возможность вводить вес модераторам  реализовна
