### ISSUE TITLE
проверка ошибок при sql-запросах

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#171]
В классе CSql в методы singleValue и аналогичные нужно добавить обработку ошибок.
1)проверять успешность MySqlQuery
2)проверять успешность mysql_fetch_assoc (вдруг select вернул пустое множество?)
3)проверять isset($row[$key]) (вдруг переменной с нужным именем нет в ответе mysql)

В случае любой из этих ошибок надо как минимум возвращать -1. А еще лучше также создать внутренние переменные с флагом ошибки и с текстовым сообщением об ошибке. И проверять на наличие ошибки во всех местах вызова метода. Также полезно писать в текстовый файл отладочную информацию с именем метода, временем, значениями переданных в него параметров. Или же отправлять письмо разработчикам об ошибке. Такие ошибки могут возникать только в случае некорректных sql-запросов и прочих форс-мажорных ситуаций и ошибку надо не только показать пользователю, но и довести до разработчиков.

**Comment by se-ti** [comment]
тут возникает отдельный вопрос про логирование
Его по-хорошему надо делать не в файлик, а в базу, в специальную табличку.
Это позволяет держать единый лог с разными типами сообщений: ошибки, трейс, отладка...
Видеть у какого пользователя это произошло, к какой функциональности относилось.
Ну и все радости поиска, какие есть в sql.

Образец кода у меня есть, поделюсь.

**Comment by se-ti** [comment]
можно еще смотреть на слово nLog

**Comment by azotov** [comment]
>Образец кода у меня есть, поделюсь.

Ты лучше сам его и добавь в класс CSql, это ведь ты его реализовал? :)

Логи в базу вполне годятся. Надо только предусмотреть ситуацию, когда, скажем, на сервере умер демон mysqld. В такой ситуации запись лога в таблицу тоже завершится с ошибкой. И в этом случае надо слать письмо на зашитый в код конкретный емейл или список мейлов с сообщением "все пропало". Ну и возможно также дублировать запись в таблицу ошибок типа critical емейлом с ошибкой на адреса админов, чтобы вовремя отследить незапланированное поведение кода.

**Comment by leonidfishkis** [comment]
У Сергея может не быть прав на создание таблиц - в этом случае нужно мне или Саше прислать струтктуру. 
>critical емейлом
можно в settings  прописать переменную для этого. $FailSafeOperator = '';

**Comment by azotov** [comment]
Да по обоим пунктам.

Логгер ошибок может быть использован и для логгирования всех действий пользователей - логины, создание/удаление команд, добавление/удаление членов команд (см.задачу #174) и других. Так что задача очень актуальная и хороший класс для этого дела будет востребован во многих местах кода.
