### ISSUE TITLE
отмена физического удаления членов команды

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#174]
Чтобы проще было отслеживать изменения в составе команд, стоит вернуть назад установку teamuser_hide=1 вместо физического удаления записей из TeamUsers.

Но не просто заменить DELETE на UPDATE при удалении участника, но и модифицировать все места, где участник добавляется в команду. Там сейчас простой INSERT, что может привести к ситуации, когда один и тот же пользователь и есть в команде, и его нет (то есть присутствуют две записи, одна teamuser_hide=0, вторая teamuser_hide=1). Чтобы такое не происходило, надо либо перед INSERT делать DELETE пользователя из команды, либо сначала делать SELECT (чтобы выяснить, вдруг пользователь в команде уже есть в удаленном состоянии), а потом INSERT или UPDATE (в зависимости от того, был обнаружен пользователь или нет).

Заодно (так как это затрагивает тот же кусок кода) предлагаю добавить новые поля в таблицы:
1)teamuser_modifydt - дата добавления или удаления участника из команды
2)team_deletedt - дата удаления команды
Это поможет лучше понимать, в какие временные промежутки команды и участники самоудаляются из списка заявившихся.

**Comment by unDina** [comment]
А это не помешает участнику записаться в другую команду, если ему нужно?
30.03.2016 17:47 пользователь "Alexander Zotov" <notifications@github.com>
написал:

**Comment by leonidfishkis** [comment]
Не должно.

Саш, а напомни, почему плохо иметь в одной команде одинаковый UserId с несколькими hide = 1  и одним hide = 0

**Comment by azotov** [comment]
2Дина - нет, везде код рассчитан на то, что если запись об участнике в TeamUsers имеет hide=1, то этого участника типа как нет. Пока физического удаления не было, записей с hide=1 накопилось в таблице довольно много и все работает корректно.

2Лёня - я не помню детали, но это ломало или импорт, или валидатор - они не могли понять, есть участник в команде или нет. Или же проблемы вылезли в ситуации, когда участник был удален, добавлен, а потом снова удален. Не помню.
В общем, участник в команде должен быть в одном из двух состояний - или он есть, или его нет. Когда он "ни жив, ни мертв", вылезали проблемы.

**Comment by leonidfishkis** [comment]
Ну так вопрос, куда допистаь проверку.  На мой взгляд (особенно если учесть твои предложения со временем модификации) лучше видеть все этапы (удалили - добавили новую запись - удалили - добавили), как отдельные.
Другой вариант прикрутить журналирование и оставить, как сейчас.

**Comment by leonidfishkis** [comment]
>от лишних hide=1, которые ломают импорт, перед началом ммб.
что-то я не увидел в коде, где это домает импорт - может плохо смотрел.
ПРоверка на teamuser_hide = 0 в import.php  стоит

**Comment by azotov** [comment]
С обычным пользователем, удаленном через teamuser_hide = 1, все мои скрипты работают корректно, такой механизм пару ммб точно использовался и все проверки у меня для него сделаны. Скрипт (кажется импорт, а не валидатор) отказался работать в ситуации, когда один и тот же пользователь дважды был зарегистрирован в одной команде. Это произошло из-за того, что ты при insert нового пользователя не проверяешь, что он уже есть в команде с флагом teamuser_hide = 1. И мы попали на ситуацию, когда пользователь был сначала добавлен в команду, потом удален, а потом опять добавлен. В результате в команде оказалось два пользователя с одинаковым user_id.

**Comment by leonidfishkis** [comment]
" В результате в команде оказалось два пользователя с одинаковым user_id."
я вижу здесь противоречие с тем, что ты написал выше про  teamuser_hide, и не понимаю, какое дело скрипту импорта, сколько записей с одинаковым user_id, если стоит проверка  where teamuser_hide = 0   Или была ошибка, что  в базе оказалось два пользователя с teamuser_hide = 0 и одинаковым ключом user_id?  Если нет такой проверки на вставку - то её можно добавить или попробовать прямо ограничение завести, если InnoDb это позволяет.

**Comment by azotov** [comment]
насколько я помню, скрипт видел, что пользователь удален из команды (есть запись с teamuser_hide = 1), но при этом присутствовал в составе команды на активных точках. Понятно, что такие запросы можно подправить, чтобы они отрабатывали корректно, в этом проблемы нет.
Мне тогда не понравилось то, что флаги *_hide исходно были введены для возможности отката удалений, а добавление удаленного пользователя назад в команду - это фактически и есть откат его удаления, но вместо отката (то есть замены в существующей записи *_hide=1 назад на *_hide=0) добавлялась новая запись и отката не происходило.

**Comment by leonidfishkis** [comment]
Вот я считаю, что здесь и возникло непонимание той логики, что я закладывал:
"скрипт видел, что пользователь удален из команды"  <> "есть запись с teamuser_hide = 1"
эту проверку надо переписать, как
"пользователь удален из команды" = "нет записи с teamuser_hide = 0"!

Теперь о истории с _hide
Во-первых, сначала у пользователя не было прав на удаление из таблиц, и таким образом достаточно прав на UPDATE и невозомжность полностью очистить таблицу при неправильном или взломанном запросе.
Во-вторых (и главных) - это позволяло не делать журналирование - архив ведётся в самой таблице.  Твоё предложение добавить туда поля changedtr  очень хорошо ложится именно на эту логику: при "восстановлении" мы не знаем, что пользователь удалялся и потом снова добавлялся, а при той схеме, что была - знаем.

На мой взгляд, всё-таик правильнее тебе переписать одну проверку на отсутствие пользователя в команде, чем менять логику на тдельное журналирование всех операций удаления и т.п.  Команда, кстати, удаляется и добавляется по тому же принципу (т.е. без update 1 на 0)
