### ISSUE TITLE
рассылка критической ошибки

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#183]
Возможно стоит не отправлять письма в ситуации, когда критическая
ошибка происходит при записи логов, а не при вызове методов класса
CSql из скриптов. Да, из-за такого самоограничения мы можем прозевать,
когда сломается логгирование, но зато уменьшим количество писем в
случае проблем.

Или же писать в файл на сервере время отправки последнего письма о
критической ошибке и не отправлять такие письма чаще, чем раз в
минуту.

P.S. И еще в письме о критической ошибке хорошо бы писать о том, какой
скрипт ее вызвал (путь к файлу скрипта) и на какой базе. Чтобы
понимать, где возникла проблема, на тестовой базе или рабочей или еще
какой.

**Comment by se-ti** [comment]
Предлагаю такие ошибки писать в файлик
Если файлик отредактирован больше, чем 5 минут назад -- слать письмо.

Хочу имя соответствующего файлика в переменной в глобальном конфиге.

Или я еще посмотрю на http://php.net/manual/ru/function.error-log.php
и http://php.net/manual/ru/function.syslog.php

Но письма все равно стоит периодически слать, так что какой-то записываемый файлик нужен
