### ISSUE TITLE
это двусмысленное слово "Регистрация"

### ISSUE THREAD

**Issue by frantony** [realtim/mmb#184]
Есть некоторая двусмысленность --- в фрейме слева уже есть ссылка "Зарегистрироваться", а в фреме справа слова "Регистрация до". 

![mmb-registration](https://cloud.githubusercontent.com/assets/416815/14936738/4594765e-0f05-11e6-958c-44f8d7d4880d.png)

Использованы однокоренные слова и можно подумать, что речь идёт об одном и том же. Однако в первом случае речь идёт о регистраиции пользователя на сайте, а во втором --- о регистрации (заявке) команды на конкретный ММБ.

Ссылка для подачи заявки называется "Заявиться", логичнее действия по заяке на конкретный ММБ всюду называть одинаково ("заявкой") и писать не "Регистрация до", а "Заявка до".

Проблема усложняется тем, что слово "Регистрация" используется во многих местах, в том числе в названиях переменных PHP (e.g. ```$RegistrationEnd```).

**Comment by leonidfishkis** [comment]
Двусмысленность возникает довольно естественно, так как предметная область одинаковая: Вы сами об этом написали - и там, и там регистрация, только в одном случае пользователя на сайте, а другом случае команды на марщ-юросок. Вы можете предложить более удачные, на Ваш взгляд, термины, чем "регистрация" (в первом случае) и "заявка" (во втором).  Ссылки, кстати, так стали называться всего лишь  неделю назад, как раз в попытке сделать более понятным.  Почему название переменных усложняют пользователям понимание интерфейса мне не ясно.

**Comment by frantony** [comment]
> Двусмысленность возникает довольно естественно, так как предметная область одинаковая:  Вы сами об этом написали - и там, и там регистрация, только в одном случае пользователя на сайте, а другом случае команды на марш-бросок. Вы можете предложить более удачные, на Ваш взгляд, термины, чем "регистрация" (в первом случае) и "заявка" (во втором).

Считаю, что термины "регистрация" и "заявка" вполне удачны, осталось только прекратить использовать термин регистрация "во втором случае".

> Ссылки, кстати, так стали называться всего лишь неделю назад, как раз в попытке сделать более понятным. Почему название переменных усложняют пользователям понимание интерфейса мне не ясно.

А разве я говорил, что названия переменных усложняют **пользователям** понимание интерфейса? Мне кажется, это у **программистов** могут быть проблемы, если "заявка" будет описываться переменными в имени которых есть слово ```Registration```.

**Comment by leonidfishkis** [comment]
>А разве я говорил
Не говорили, поэтому возникла двусмысленность в употреблённом Вами слове "проблема" -  вот я и уточнил.

**Comment by frantony** [comment]
Леонид! Хорошим тоном является при закрытии issue давать ссылку на commit, который исправляет описанную в issue проблему.

**Comment by realtim** [comment]
Уважаемый @frantony, вам не кажется, что ваш комментарий не соответствует хорошему тону роли, которую вы в этом issue играете?
