### ISSUE TITLE
Неправильно работает сортировка по ошибкам

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#187]
Нужно, чтобы работало как раньше - команды с ошибками выводились первыми в
режиме сортировки по ошибкам и для каждой команды с ошибками в поле
комментария выводилось текстовое описание ошибки и точка, на которой эта
ошибка произошла.

**Comment by azotov** [comment]
Сортировка у тебя по порядковому номеру точки, на которой зарегистрирована ошибка? Да, нормальный вариант.
Я бы несколько подкорректировал генерацию текста комментария и формулировки ошибок, но это я сам могу сделать через пару дней.
Выкатил на рабочую, есть только одна проблема:
Если сделать пересчет результатов, то после него список команд с ошибками оказывается пустым. Это неправильно - если валидатор поставил команде ошибку на точке, то она должна сниматься следующим прогоном валидатора (если, конечно, ошибка в данных была исправлена) или вручную, а не пересчетом результатов. team_minlevelpointorderwitherror при пересчете результатов не обнуляется, проблема где-то еще.

**Comment by leonidfishkis** [comment]
>Это неправильно 
Это следствие того, что часть ошибок проставляется в пересчете результатов, когда ещё схема не утрясладсь с валидатором, и поэтому там же в самам начале расчета обнуляется. На мой взгляд, ошибки, которые можно ловить sql запросами будут работать быстрее, чем аналогичный проход валидатора, но  настаивать   я не буду - разве что советую тебе посмотреть код простановки ошибок и перенести его в свой валидатор.
team_minlevelpointorderwitherror  дожен просто агрегировать текущие данные об ошибках, которые проставлены в точках - не важно, сделал ли это валидатор иил пользователь.
Итого: я убираю из пересчета все простановки ошибок и их обнуление?
