### ISSUE TITLE
На половине смартфонов loggermanger не подключается к логгерам 

### ISSUE THREAD

**Issue by yuriyweiss** [realtim/mmb#213]
На прошедшем ММБ у половины волонтёров приложение loggermanager на телефонах отказалось работать с логгерами по Bluetooth.
Необходимо исправить ошибку.
Есть предположение, где находится ошибка. Но т.к. у меня нет устройств Lenovo, то проверить исправление можно будет только на брифинге.

**Comment by jekyll2014** [comment]
Юра,

А ты можешь выложить приложение для всех и снять фильтр на БТ-имя
устройства? Тогда можно попробовать на разных приборах...

**Comment by jekyll2014** [comment]
Юра,

Кстати, я могу поместить на нескольких телефонах из домашней коллекции... И
на разных знакомых...

Батарейки для логгеров я все проверил зарядом/разрядом - все >=2500 мАч.
Завтра еще логгеры и сканеры погоняю...

**Comment by yuriyweiss** [comment]
Фильтр на список БТ-устройств снял.

**Comment by yuriyweiss** [comment]
На прошедшем ММБ таких проблем не было.
Реализовано два режима работы с bluetooth, переключаются залипающей кнопкой "Старый/Новый".
