### ISSUE TITLE
Добавить в валидатор режим пропуска ОКП. 

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#218]
Публикация данных заметно задерживается проверками, хотя исхожные данные по важнейшим точкам есть практически сразу

**Comment by azotov** [comment]
Напишу здесь, чтобы не забыть:
сделать в интерфейсе отдельную кнопку, которая обнуляет все ошибки, поставленные автоматически валидатором. Это позволит "получить место" тем командам, для которых валидатор нашел ошибки, что может быть актуально, если ошибка присутствует для всех команд, а хочется опубликовать результаты.

**Comment by azotov** [comment]
Уже не актуально в связи с переходом на электронную отметку - сейчас все данные сразу поступают на сайт и не может быть задержки из-за отсутствия данных с ОКП. Валидатор наверняка придется модифицировать, но под это будет отдельный issue после его тестирования осенью 2019
