### ISSUE TITLE
Метрики: Приход новичков

### ISSUE THREAD

**Issue by cornet1973** [realtim/mmb#235]
Количество новичков, вышедших на старт по категориям:
- В составе чисто новичковых команд.
- В составе команд, где есть хотя бы один опытный участник не имеющий рейтингового приглашения.
- В составе команд, где есть хотя бы один участник с рейтинговым приглашением.

**Comment by leonidfishkis** [comment]
Важный момент - это не стартовавших, а всех зарегистрированных и не удаленных.
Если учитывать тех, кто стартовал, то терятт смысл  понятия "чисто новичковая"  "с опытынм" - ведь стартовать мог  только новичок, а заявиться новичок с опытным.
Можно попробовать добавить информацию, сколько новичков стартовало в команде.

**Comment by cornet1973** [comment]
Стартовавшие - это в других метриках прописано. Здесь же именно процес регистрации интересен.

А возможно получить аналогичные распределения по нескольким предыдущим ММБ?
Понятно что там придётся объединить в одно 2 показателя нынешнего ММБ, ведь приглашений не существовало:
# в командах с опытным участником без приглашения по рейтнгу
# в командах с опытным участником, имеющего приглашение по рейтнгу

**Comment by leonidfishkis** [comment]
Обновленные запросы

create table stat_NewTeamUsers as
select a.team_id
		, MAX(a.raid_id) as raid_id 
		, count(tu1.teamuser_id) as teamuserscount
		, MAX(a.newcount) as newcount		
		, MIN(CAST(tu1.teamuser_new as SIGNED INTEGER)) as minnew
		, count(inv.user_id) as invcount
from
	(select tu.team_id, count(*) as newcount, MAX(d.raid_id) as raid_id
	from TeamUsers tu
			inner join Teams t 
			on t.team_id = tu.team_id
			inner join Distances d
			on t.distance_id = d.distance_id
	where t.team_hide = 0
		and tu.teamuser_hide = 0
		and tu.teamuser_new = 1
		and d.raid_id >= 19
	group by tu.team_id
	) a
inner join TeamUsers tu1
on a.team_id = tu1.team_id
left outer join
(select  invd.raid_id, inv.user_id
from Invitations inv
inner join InvitationDeliveries invd
on inv.invitationdelivery_id = invd.invitationdelivery_id
#where invd.raid_id = a.raid_id
and invd.invitationdelivery_type = 1
) inv
on tu1.user_id = inv.user_id
   and a.raid_id = inv.raid_id
where tu1.teamuser_hide = 0
group by a.team_id

create table stat_NewTeamUsersForRaids as
select  s1.raid_id, s1.allnewcount, s2.allintruenewteam, 
		s3.allinteamwithoutinvitation, s4.allinteamwithinvitation
from
(
	SELECT raid_id, SUM(newcount) as allnewcount 
	FROM stat_NewTeamUsers 
	GROUP BY raid_id #всего новичков
) s1
left outer join 
(
	SELECT raid_id, SUM(newcount)  as allintruenewteam
	FROM stat_NewTeamUsers  
	WHERE minnew = 1  
	GROUP BY raid_id #в чисто новичковых командах
) s2
on s1.raid_id = s2.raid_id
left outer join 
(
	SELECT raid_id, SUM(newcount)  as allinteamwithoutinvitation
	FROM stat_NewTeamUsers  
	WHERE minnew = 0 and invcount = 0
	GROUP BY raid_id  # в командах с опытным участником без приглашения по рейтнгу
) s3
on s1.raid_id = s3.raid_id
left outer join 
(
	SELECT raid_id, SUM(newcount)  as allinteamwithinvitation
	FROM stat_NewTeamUsers  
	WHERE minnew = 0 and invcount > 0
	GROUP BY raid_id  #  в командах с опытным участником, имеющего приглашение по рейтнгу
) s4
on s1.raid_id = s4.raid_id

и результаты 
[stat_newteamusers.zip](https://github.com/realtim/mmb/files/596885/stat_newteamusers.zip)
