### ISSUE TITLE
Пользователи со знаком (?!) получили рейтинговые приглашения

### ISSUE THREAD

**Issue by cornet1973** [realtim/mmb#258]
По результатам генерации рейтинговых прглашений Весна 2017

Примеры

Команда:
http://mmb.progressor.ru/php/mmbscripts/index.php?TeamId=31040&RaidId=29 
команда активирована приглашением аккаунта: http://mmb.progressor.ru/php/mmbscripts/index.php?UserId=311 
который 2 раза за последние регистрации не являлся на старт.
У аккаунта стоит знак (?!), при этом в рейтинге знак !! отсутствует.

Команда:
http://mmb.progressor.ru/php/mmbscripts/index.php?TeamId=31232
активирована приглашением аккаунта http://mmb.progressor.ru/php/mmbscripts/index.php?UserId=1650
У аккаунта стоит знак (?!), при этом в рейтинге знак !! отсутствует.

Ожидаемый результат:
1. Аккаунты имеющие знак (?!) так же должны иметь знак !! в рейтинге.
2. Аккаунты имеющие знак (?!) не должны получать рейтинговых прглашений, по причине п.1.

**Comment by leonidfishkis** [comment]
Примеры не говорят о неправильной работе  алгоритма выдачи приглашений:
1. Бондаренко Роман.   Неявка на старт стоит осенью 2015, а весной 2016 стоит 0.00, но не стоит "Команда не вышла на старт в полном составе", потому что команда "вне зачета", а для таких команд вообще не имеет смысла следить. Итого на момент запуска пересчета  рейтинга  при расчете результатов   "Осень 2016 года"  не было повода ставить флаг !! и не выдавать приглашение
2. Коновалова Любовь. Неява на старт стоит осенью 2015. Таким образом человек не снял с себя до ввода приглашений и наказывать ли его по новым правилам (задним числом) вопрос спорный. Скорее всего я его обсуждал в рассылки, и скорее всего решили не наказывать.
 
Однозначной ошибкой будет наличие приглашения у человека, чья команда не явилась на старт  (и это отмечено в базе) осенью 2016 года.  Если такие примеры?

**Comment by leonidfishkis** [comment]
Знак ?!  присваивается не аккаунту, а участнику конкретного ММБ, если он не явился на предыдущий ММБ. Знак связана со знаком аккаунта !!, но  только в одну сторону: для !! необходимо, но не достаточно, знака ?! в последенем ММБ.
