### ISSUE TITLE
Оптимизация импорта с планшетов в базу

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#263]
На больших файлах скрипт импорта может работать так долго, что броузер/прокси разрывают соединение по таймауту. При этом на сервере скрипт продолжает свою работу (что невозможно понять без мониторинга базы данных) и повторный запуск импорта в тот момент, когда первый импорт еще не завершился, приводит к дублям в базе.

Надо:
-более агрессивно кешировать результаты sql-запросов, чтобы импорт шел побыстрее.
-добавить вывод счетчика количества загруженных строк, чтобы прокси/броузер понимали, что страница еще в процессе генерации, а не зависла
-возможно стоит добавить отдельную таблицу, в которой на время импорта создавать запись, сигнализирующую о том, что идет импорт, база находится в состоянии lock и еще один импорт запускать нельзя.

**Comment by leonidfishkis** [comment]
Возможно стоит попробовать использовать временные таблицы. Расчет результатов это существенно ускорило. А для индикации ты можешь не создавать таблицу, а писать в лог, а потом оттуда читать, что последняя по времени запись с ключевыми словами о старте процесса, а  нет об окончании.

**Comment by azotov** [comment]
Уже не актуально в связи с переходом на электронную отметку.
