### ISSUE TITLE
Ошибка при автозаполнении комментария у команды

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#266]
При наличии ошибки на одной из точек у команды текст об этой ошибке записывается в team_comment дважды (это происходит и при редактировании результатов команды, и при пересчете результатов всех команд). Сейчас это наблюдается у команд 418 и 1072 - у них отсутствует время только на одном ОКП, а текст об этом повторяется дважды. Лёня, это твоя ошибка.

Кроме того, при удалении автоматически сгенерированных ошибок скриптом поиска ошибок не перегенерируется комментарий, поэтому у команд, у которых ошибки исправлены, текст об этих ошибках остается в team_conmment. Это моя ошибка.

**Comment by leonidfishkis** [comment]
Я поправил
