### ISSUE TITLE
При объединении  4х команд (больше 2х?) возникает ошибка 

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#272]
Скрипт выдает "Различается список взятых КП" при том, что он не различается.
Решается тем, то команды объединяются по две. 
Пример объединение команд 1210 и 1209 (точнее исходных 81, 27, 347, 474)

**Comment by leonidfishkis** [comment]
Также возникает проблема при повторном запуске объединения - создаются две команды

**Comment by banga73** [comment]
Объединение четырех команд прошло успешно:
- объединенные команды были разъединены
- потом объединены обратно. Ошибки не возникло
