### ISSUE TITLE
некорректное удаление точки дистанции

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#277]
При удалении точки через интерфейс сайта администратором некорректно пересчитывается поле levelpoint_order для оставшихся точек.

В результате для двух точек дистанции получается одинаковый levelpoint_order, а в некоторых местах на сайте и в приложении код верятно написан с предположением, что levelpoint_order у всех точек уникальный, и у них начинают лезть всякие глюки.

Предлагаю кроме непосредственного исправления бага подправить и структуру базы, сделав пару levelpoint_order+distance_id уникальной. Это будет полезно и для электронной отметки, так как станции работают именно с levelpoint_order в качестве номера КП, а не с levelpoint_id. Экспорт для нового приложения обнаружит дубликаты, но лучше их запретить совсем ограничем в таблице базы.

**Comment by leonidfishkis** [comment]
Скорее всего, ошибка возникает при попытке удалить точку, на которую уже есть информация а дочерней таблицы (амнистии или результаты команд). Нужно добавить проверку на все дочерние таблицы, как это сделано в scanpoints и проверять, что точка успешно удалилась, прежде, чем сдвигать.   
Ограничение сейчас поставить нельзя, так как сначала нужно переписать процедуры поднятия и опускания точки, чтобы в них это ограничение (пусть на короткое время) не происходило.
