### ISSUE TITLE
количество карт

### ISSUE THREAD

**Issue by traktor42** [realtim/mmb#281]
в [вики](https://github.com/realtim/mmb/wiki/%D0%97%D0%B0%D1%8F%D0%B2%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B,-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%BE%D0%B9-%D0%BD%D0%B0-%D0%9C%D0%9C%D0%91) (или в Положении) хотелось бы видеть ответ, до какого момента можно изменить количество комплектов карт

**Comment by leonidfishkis** [comment]
Поправил в статью.
