### ISSUE TITLE
Добавить условие отбора точек в показ

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#283]
https://github.com/realtim/mmb/blob/22e8e3ad191e6fe1f8edb10eac3ef4c1a47abd35/site/functions.php#L3626

С вводом электронной отметки число точек заметно выростет. Нужно будет добавить условие отбора  временных отчесек (точки типа старт, финиш, смена карт). Для этого нужно добавить join  с таблицей  LevelPoints  и отфильтровать pointtype_id (1,2,4)

**Comment by banga73** [comment]
Все работает. Багов не замечено
