### ISSUE TITLE
Добавить в GetStatus уровень заряда батареек станции

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#288]
Надо убедиться, что станция при садящихся батарейках четко находится в одном из двух режимов - сначала все работает, потом ничего не работает (без сбойного режима частичной работы посередине). И что волонтеры могут легко заметить, что батарейки сели и пора их заменять.

Если GetStatus будет возвращать уровень заряда батареек в процентах в качестве одного из параметров, то это будет вообще идеально - я смогу показывать в приложении совет заменить батарейки, пока они не сели окончательно.

**Comment by alexandervolikov** [comment]
Там у Atmega328p есть внутри опорник на 1.1 вольта. После стабилизатора на 3.3 вольта, понятно, не определить, напряжения батарей, если оно выше 3.3 вольт. Но, если снижается, то можно. То есть, можно как раз выявить момент когда у батарей осталось 10-15% заряда и что-то сделать, например, выключить станцию совсем.
Для станций отметок я это реализовал на основе статьи:
https://web.archive.org/web/20131203102641/http://provideyourown.com/2012/secret-arduino-voltmeter-measure-battery-voltage/

В моём коде к станции это 406-456 строки
https://github.com/alexandervolikov/sportiduino/blob/b90060f7dbb2fbcfcb7f518db698e1916ebaa4f6/Base%20station/firmware/BaseStation/BaseStation.ino

**Comment by crosser** [comment]
потенциально можно было бы поделить напряжение перед стабилизатором и подать на компаратор например 1/4 от того что дает батарейка... Не зная конструкции устройства нельзя оценить насколько эта идея практична. И насколько нежелателен дополнительный drain на делителе.

**Comment by jekyll2014** [comment]
Да, идея с внутренним источником опорного напряжения 1.1В хорошая.
Сделаю делитель на ~10кОм и реализую в прошивке.

**Comment by azotov** [comment]
Реализовано. Закрываю.
