### ISSUE TITLE
Критически медленная работа ChipInit

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#290]
Сейчас эта функция выполняется станцией 8 секунд. Это слишком долго, сейчас у нас волонтеры выдают бумажные карточки гораздо быстрее. При анализе кода я не могу сходу сказать, где проблема. Но предполагаю, что технически реально записать все данные в чип гораздо быстрее. В приложении NFC Tools на телефоне операции и "Erase Tag", и "Format memory" с тем же чипом выполняются менее секунды.

**Comment by alexandervolikov** [comment]
На станции сопряжения, подключенной к компьютеру, у меня это осуществляется где-то за 4 секунды. То есть, ускоряться есть куда, но все равно сравнительно медленно, проблема в дешевых модулях RC522. С другой стороны, инициализацию можно упростить.
Сейчас она происходит в три этапа:
1. Сначала записываются во все страницы чипы единицы (с проверкой факта записи)
2. Затем записываются во все страницы нули (с проверкой факта записи)
3. Затем записывается информация в 4-8 страницы

1 и 2 пункт нужен, чтобы убедиться, что вся память чипа работает правильно. 
Можно выполнить пункт 1-2 дома для всех чипов, можно придумать какой-нибудь флаг, который пишется в определенную страницу при условии выполнения проверки. А на самом старте просто проверять флаг и записывать информацию в 4-8 страницы.

**Comment by azotov** [comment]
Сейчас судейская станция инициализирует чип за 4-5 секунд, что терпимо. Закрываю.
