### ISSUE TITLE
Не подключаться к станции без скачанной с сайта базы

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#292]
Сейчас теоретически любой участник может скачать приложение, установить себе на телефон, подключиться к станции и сделать Reset, что приведет к удалению всех результатов команд из станции. Вероятность этого небольшая, да и приложение будет постоянно скачивать все новые данные из станции.
Но все равно лучше запретить подключение к станции без скачанной с сайта дистанции. Этим мы оставим возможность подключения к станции из приложения только  оргам и волонтерам текущего марш-броска.

**Comment by jekyll2014** [comment]
Решено использовать защиту паролем соединения по BlueTooth.
Смену пароля реализовать командой в прошивке станции.
