### ISSUE TITLE
Favicon для ММБ

### ISSUE THREAD

**Issue by realtim** [realtim/mmb#3]
Хочется сделать favicon (иконку сайта) для mmb.progressor.ru. Есть идеи как она должна выглядеть?

**Comment by santiago26** [comment]
А почему закрыли этот реквест? Также реквестую.

**Comment by leonidfishkis** [comment]
Закрыл, т.к. никто не взялся это делать.

**Comment by santiago26** [comment]
Моя концепция фавиконки для ММБ такая:
![favicon 128px](https://cloud.githubusercontent.com/assets/1297578/6768659/95cc04f8-d08a-11e4-824a-f05608c442ef.png)
Но попиксельно отрисовать букву М я не смог, поскольку не тру дизайнер. Может быть друзей-дизайнеров попрошу, а пока можно взять обычную ориентировочную призму:
![favicon 16px](https://cloud.githubusercontent.com/assets/1297578/6768655/6bae58ec-d08a-11e4-98b8-c8c11789af3d.png) ![favicon 32px](https://cloud.githubusercontent.com/assets/1297578/6768654/6badca26-d08a-11e4-858b-624eca87dde8.png) ![favicon 64px](https://cloud.githubusercontent.com/assets/1297578/6768653/6badb342-d08a-11e4-9c9d-893dfbba2746.png) ![favicon 128px](https://cloud.githubusercontent.com/assets/1297578/6768656/6bae596e-d08a-11e4-9aaf-948466728045.png)

**Comment by santiago26** [comment]
Если допустимо чуть-чуть изменять начертание буквы М, то я её вписал в призму. Таким образом, в картинке есть призма, буква "М",а то, что под буквой "м" напоминает пень (можно и
![favicon 16px](https://cloud.githubusercontent.com/assets/1297578/6769111/5f3ebd76-d09f-11e4-8130-864e2a3295c7.png) ![favicon 32px](https://cloud.githubusercontent.com/assets/1297578/6769112/5f58d94a-d09f-11e4-8e45-d6e4faf976ca.png) ![favicon 64px](https://cloud.githubusercontent.com/assets/1297578/6769113/5f6a694e-d09f-11e4-9678-d1fa33249a5b.png) ![favicon 128px](https://cloud.githubusercontent.com/assets/1297578/6769114/5f6b4a30-d09f-11e4-93d5-c62caaf68aee.png)

**Comment by azotov** [comment]
Последний вариант сморится неплохо, я бы только попробовал еще сделать букву М зеленой (как в слове "весна" в логотипе этого года) - на мелких размерах иконки красная М слегка сливается с красной призмой.

**Comment by santiago26** [comment]
![favicon 16px](https://cloud.githubusercontent.com/assets/1297578/6780999/0c9a5cec-d17b-11e4-8c34-6a5ef119a125.png) ![favicon 32px](https://cloud.githubusercontent.com/assets/1297578/6781005/1c86f868-d17b-11e4-9cc5-0a7c0fef714f.png)![favicon 64px](https://cloud.githubusercontent.com/assets/1297578/6781030/45f16350-d17b-11e4-96ab-6840ff9574ae.png)![favicon 128px](https://cloud.githubusercontent.com/assets/1297578/6781029/45f06f36-d17b-11e4-8bf7-62e482ec2750.png)

**Comment by leonidfishkis** [comment]
Призмы на ММБ никогда не использовались  в качестве КП.
Может не стоит обыгрывать название - его всё равно никто не разглядит, а  взять в гамме карты красный кружок КП и две стрелки (точнее кусочек приходящей и уходящей линии), а часть фона  сделать зелёным?

**Comment by realtim** [comment]
@santiago26 попробовал связаться с тобой через jabber, задать пару вопросов про разработку, не получилось. Можешь постучаться?
У меня такой же как здесь ник на jabber.ru

**Comment by santiago26** [comment]
@leonidfishkis ну да, название можно обыгрывать только на больших лого, в маленьком варианте букв и нету.
Попробовал варианты с КП — не очень, по-моему:
![favicon- 16px](https://cloud.githubusercontent.com/assets/1297578/6865732/fa47f482-d481-11e4-94b9-38bd2f5b48f9.png) ![favicon 3 16px](https://cloud.githubusercontent.com/assets/1297578/6865733/fd11387c-d481-11e4-90e9-006696f63b9b.png)
Пробовал добавлять букву "М" в центр круга. И белая, и чёрная неразличимы. А на обводку места не остаётся, за пределы КП вылезаем.

// С realtim - связались

**Comment by dichlofos** [comment]
Я сколхозил из значка 2012 года вот такое: https://yadi.sk/i/z2-N2rpfoSSdb
Попробовал его в качестве фавиконки -- надпись ММБ вполне различима. Мне кажется, это будет сильно лучше, чем ничего.

**Comment by leonidfishkis** [comment]
Спасибо, выложил.
