### ISSUE TITLE
Корректная работа при отсутствии для дистанции точек сканирования

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#303]
Таблица ScanPoints больше не используется - у нас больше не будет точек сканирования. Соответственно, надо убрать все запросы к ней в коде (если это не сломает показ старых ммб), ну или как минимум сделать так, чтобы все показывалось корректно в ситуации, когда у марш-броска нет ни одной точки сканирования. Сейчас показывается некорректно как минимум таблица результатов в карточке команды - вторая колонка с именем "Время" и колонка с именем "Результат" стали пустые.

Для корректного отображения результатов команды надо иметь в виду, что раньше мы были уверены, что команда посещала точки сканирования (где у нее было время на точке) в порядке возрастания номеров точек сканирования. Сейчас у каждой точки есть время посещения и команды посещали их точно не в порядке их номеров (в облаках порядок посещения может быть произвольным). Поэтому вероятно в таблице результатов точки надо показывать не в порядке увеличения их номера, а в порядке взятия конкретной командой. Но при этом не сломать алгоритм показа для прошлых ммб.

**Comment by leonidfishkis** [comment]
>вторая колонка с именем "Время" и колонка с именем "Результат" стали пустые.
Я нажал на первую команду в тестовой базе http://mmb.progressor.ru/php/mmbscripts_git/index.php?TeamId=35559&RaidId=33  Время и результат заполнены.

**Comment by azotov** [comment]
Проверил, сейчас действительно показываются эти две колонки. Правда в колонке Результат вроде числа правильные, а в колонке Время они явно не те (местами вообще отрицательное время). Что там вообще должно показываться, чистое время без учета штрафов или время в пути между предыдущим КП и текущим?

**Comment by leonidfishkis** [comment]
Ну алгоритм сортировки (он, кстати, не связна со scanpoints) задается порядковым номером активной точки - так же считаются и результаты - вот время и отрицательное. Думаю, что общий результат при этом считается правильно.  Я попробую поменять порядок сортировки.

**Comment by azotov** [comment]
Да, в идеале надо сортировать в порядке взятия КП - теперь у нас все КП со временем взятия, так что порядок взятия определяется легко. Только не сломать бы показ для предыдущих ммб...

**Comment by leonidfishkis** [comment]
см. выше - я обновил - если станция полностью вышла и её решили зачесть

**Comment by azotov** [comment]
Да, для показа таблицы результатов одной команды такая логика "по времени/по номеру" вполне подойдет. А для общего списка команд и их результатов можно оставить логику "по номеру" - там должны показываться только С/СК/ПФ/Ф, а команды будут их брать в любом случае именно в этом порядке, и ситуации, когда у нас на такой судейской точки нет времени, быть не должно (то есть, конечно, может быть разовый случай, когда станция не сработала, но такой команде можно и вручную время прописать).

**Comment by leonidfishkis** [comment]
Посмотрел, вроде в общем показе достаточно только отфильтровать правильно активные точки.  Пролблема останется в расчетом результатов . Как вариант считать, что расчет "по-старому"  больше никогда запускаться не будет и  "по умолчанию" считать  "по времени", а в твой валидатор добавить ошибку, чтобы на точку без времени всегла вешалась ошибка. Так будет понятно, поему отображение (или рассчет результатов) для конкретной команды "сломался".  Если считать, что выпадает всегда "не крайняя" точка, то время такой выпавшей токи можно принудительно ставить "старт" + 1 минута.  Это также позволит оставить только одну сортировку "по времени" для "новых" ммб, но при этом надо не забыть, что для старых ммб вывод   должен быть "по номеру".

**Comment by leonidfishkis** [comment]
Сделал новое отображение - можно смотреть.  Расчет результатов пока не менял

**Comment by banga73** [comment]
Тестовая запись
