### ISSUE TITLE
Адаптировать таблицу результатов команд под электронную отметку

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#305]
Как и предполагалось, поле "Отсечки времени" в таблице результатов команд сломалось. Там нужно показывать не все времена на точках, которые есть для данной команды в базе, а только времена на точках типа старт, СК и финиш.

А вот в выпадающем списке "фильтровать по точке" вероятно можно предлагать все-все точки дистанции, для которых у команд есть время посещения, а не только факт посещения (чтобы можно было посмотреть, в каком порядке, скажем, команды посетили КП Сплава).

**Comment by leonidfishkis** [comment]
@azotov  на мой взгляд, это дублирует задачу 33. которая стоит "для тестирования"

**Comment by banga73** [comment]
Да, мне тоже кажется, что это дубль 283. В ней отписалась, все работает.
