### ISSUE TITLE
Сделать mmb.progressor.ru доступным по https

### ISSUE THREAD

**Issue by tarwirdur** [realtim/mmb#328]
Причины:

 * браузеры все агрессивнее предупреждают пользователя о небезопасности http
 * многие люди используют один и тот же пароль для доступа к разным сервисам включая сайт ММБ. Нехорошо что пароль передается открытым текстом

Почему это всё ещё не сделано? Нагрузка на сервер не должна заметно вырасти из-за шифрования.

**Comment by azotov** [comment]
Тут все просто - переход на https уже давно в планах, но пока висит в очереди из-за нехватки времени. Времени надо не так много, но все равно вечер целиком потратить придется. Поэтому сейчас, когда находится свободное время, я занимаюсь другими, более срочными вопросами. К сожалению, именно переход на https завязан только на меня, больше его реализовать из разработчиков некому.

**Comment by tarwirdur** [comment]
> К сожалению, именно переход на https завязан только на меня, больше его реализовать из разработчиков некому.

Если нужно - могу посодействовать. На кучу доменов получаю сертификаты от letsencrypt через [dehydrated](https://github.com/dehydrated-io/dehydrated). Не должно занять больше часа.

// [Артём](http://mmb.progressor.ru/?UserId=1309)

**Comment by azotov** [comment]
Спасибо за предложение) Я сам не раз это настраивал с помощью acme.sh, но под FreeBSD и валидация через DNS, а тут надо будет под CentOS и валидация через http. Разберусь, конечно, просто надо будет аккуратно проверить все мелочи, чтобы в самый неподходящий момент не оказаться с протухшим сертификатом))

**Comment by tarwirdur** [comment]
> валидация через DNS

дык по http технических сложностей куда меньше.

В общем если вдруг будет нужна помощь по администрированию linux - можешь подключать. (а вот с bsd хоть и общался, но мало)

>  acme.sh

Судя по документации на `acme.sh`, `dehydrated` проще в использовании.

1. Скачать sh куда-нибудь в /opt
2. скачать `
dehydrated/docs/examples/` в /etc/dehydrated
3. прописать путь до hook.sh в config
4. в hook.sh в deploy_cert добавить reload веб-сервера.
5. В веб-сервере настроить .well-known
6. добавить домен в domains.txt
7. `./dehydrated --register`
8. `./dehydrated -c`
9. добавить `/opt/dehydrated -c` в cron.

**Comment by azotov** [comment]
Сделано. Надо только не забыть проверить через 3 месяца, что продление сертификата работает корректно.

**Comment by tarwirdur** [comment]
Ура! Спасибо.

> Надо только не забыть проверить через 3 месяца

Обычно продление происходит за 30 дней до окончания. Так что проверить можно будет 09.06.
