### ISSUE TITLE
не отдаётся json 

### ISSUE THREAD

**Issue by z4zz** [realtim/mmb#342]
текст ошибки:
`Fatal error: Uncaught Error: Class 'ZipArchive' not found in /usr/share/nginx/html/php/mmbscripts/teamaction.php:974 Stack trace: #0 /usr/share/nginx/html/php/mmbscripts/index.php(133): include() #1 {main} thrown in /usr/share/nginx/html/php/mmbscripts/teamaction.php on line 974`

**Comment by azotov** [comment]
yum install php-zip
service php-fpm restart
Вроде заработало. Проверьте на всякий случай.

**Comment by z4zz** [comment]
заработало, спасибо!
