### ISSUE TITLE
Ревизия регистрации схода команд и участников

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#69]
Проверить структуру базы, чтобы и для команд, и для участников во всех таблицах базы была возможность поддерживать два варианта схода на этапе - невыход на этап и сход с этапа в процессе его прохождения. Поменять структуру базы и интерфейс к базе для реализации этого требования. Убедиться, что результаты команд прошедших ММБ показываются точно также, как показывались раньше. Проверить, не сломалось ли что-нибудь в импорте с планшетов.

**Comment by leonidfishkis** [comment]
Задание тестно свзяано с общим переходом на точки.
