### ISSUE TITLE
Отметка в списке участников и генерация суммы к оплате

### ISSUE THREAD

**Issue by leonidfishkis** [realtim/mmb#89]
Вывести отметку для тех участников текущего ммб, кто на предыдущем ммб не вышел на старт (и не удалили себя из команды или команду целиком)

**Comment by leonidfishkis** [comment]
Добавить поле "Штраф за неявку"  в атрибуты Марш-броска и сделать генерацию суммы для команды по принципу:
число карт * цена карты + число ?! * штраф
Эту сумма передаётся в отчёт для печати карточке и дамп для планшетов.

**Comment by realtim** [comment]
Я как-то упустил эту идею. Речь про денежный штраф? А как он пересчитывается, если состав команд поменялся?

**Comment by leonidfishkis** [comment]
Да. 
Есть участник текущего ММБ.  Программа находит предыдущий ММБ, в котором этот пользователь участвовал и смотри статус. Если команда не вышла на старт (того ММБ) и участник (тогда) себя не удалил, то  этому пользователю начисляется штраф, который включается в стоимость команды на текущем ММБ.  Сумма "к оплате" считается, как штраф всех участников + стоимость всех комплектов карт. Эта сумма отображается в карточке команды на сайте и печатается на карточке.

**Comment by unDina** [comment]
А выпускающие на старте не опухнут выяснять, кто сколько должен заплатить?

22 июня 2015 г., 13:46 пользователь Leonid Fishkis <notifications@github.com

**Comment by leonidfishkis** [comment]
Что значит выяснять - я же написал, что сумма вбивается в карточку.
Сейчас выпускающий тоже тратит время на умножение числа карт на стоимость,
вместо этого он смотрит в карточку и называет сумму.


22 июня 2015 г., 13:54 пользователь unDina <notifications@github.com>
написал:

**Comment by leonidfishkis** [comment]
Переделал алгоритм отображения: теперь в таблице TeamUsers  есть новое поле
teamuser_notstartraidid, которое считается один раз при  добавлении пользователя в команду и содержитт ключ предыдущего марш-бросок, на котороый пользователь заявился, но не вышел на старт.   Вычисление штрафа использует это поле и отоюражение занка ?! также будет использовать это поле.
