### ISSUE TITLE
Обновление визуального стиля

### ISSUE THREAD

**Issue by santiago26** [realtim/mmb#95]
Будет ли интересно организаторам изменить внешний вид сайта в сторону осовременивания?

Могу перевести сайт ММБ на какой-нибудь из существующих фрейморков вроде Bootstrap.
В черновом варианте это у меня вышло как-то так:
![default](https://cloud.githubusercontent.com/assets/1297578/6765194/dd986640-cfe6-11e4-8240-567b239611bd.png)

**Comment by leonidfishkis** [comment]
Мне нравится идея. Если, конечно, остальные разработчики не против.

**Comment by santiago26** [comment]
Сгенерировал ещё один вариант, чтобы можно было повыбирать. Речь всё ещё про выбор стиля, обращайте внимание на него.
Расположение элементов изменилось, но его целесообразно изменять при любом стиле. 
![default](https://cloud.githubusercontent.com/assets/1297578/6769089/32fcebbc-d09e-11e4-9f43-bed3db56aabe.png)

**Comment by azotov** [comment]
Я частично за идею:

К использованию фреймворков отношусь с большим сомнением. Это связано со взаимозаменяемостью разработчиков. Обычным php (и SQL в плане запросов) мы все владеем и можем править чужой код. А если фреймворк будет знать только один из разработчиков, то остальным будет сложно, если потребуется быстро подправить его код или же он потом уйдет из проекта. Понятное дело, что любой фреймворк можно освоить, но на это уйдет время, которого постоянно не хватает :)

А вот к изменению дизайна сайта с помощью CSS (ну и небольшой перекомпоновки и улучшению usability) я отношусь очень хорошо. Единственный момент - цветовая гамма. Я бы сайт сохранил в зеленых тонах (зеленый как в слове "весна" в логотипе) или попробовал бы красный цвет (как в слове "ММБ"), а не вводил бы еще один дополнительный цвет, как в примерах.

**Comment by leonidfishkis** [comment]
>К использованию фреймворков отношусь с большим сомнением. Это связано со взаимозаменяемостью разработчиков

Если нам помогут выучить это фреймворк, то почему нет?

Вопрос к santiago26
Как технически предлагается "перевести сайт ММБ на какой-нибудь из существующих фрейморков вроде Bootstrap".  Хочется посмотреть на черновые страницы изнутри и понять, что нужно в песочнице менять.

Про цвета согласен с Сашей. 
На мой взгляд, нужно учесть следующее при перекомпоновке:
1. Сейчас много пунктов завязано на выбранный в списке ММБ. Впечатления, кстати, тоже   планируется завязать . Значки теперь доступны через Файлы, и я не уверен, что вообще нужна отдельная ссылка на статическую страницу.
2. Пояснение по форме поиска, на мой взгляд, занимает ценное место и может быть убрано в ссылку (подвал или скрываемый блок)

**Comment by santiago26** [comment]
@azotov чтобы учесть это беспокойство, в таком случае нам, видимо, стоит выбрать более распространённый фреймворк Twitter Bootstrap, документацией  (а не Foundation, который я показывал в самом первом скриншоте).
Возможноя ещё должен уточнить, что речь и шла о кастомизации стредствами css. Bootstrap- это css-фреймворк. Как следствие, классы фреймворка очень удобно переопределять. Не нужно изучать внутреннее устройство, чтобы использовать. Вся работа по кастомизации ведётся в отдельном файле с чистым css и также имеет низкий порог вхождения. 
Ещё одна польза от фреймворков - множество готовых тем. Например, одной строчкой из зелёной темы получается красная:
![default](https://cloud.githubusercontent.com/assets/1297578/6779843/2a2a7eb8-d171-11e4-953c-c4bb63d00a20.png)
Хотя, конечно, не всегда можно применить тему и больше ничего не делать, иногда надо адаптировать проект.

@leonidfishkis вместо текущего mmb.css в index.php будем инклюдить css-файл фреймворка. Вместо классов из mmb.css и инлайновых стилей в menu.php и других страницах прописываются css-классы фреймворка.
Я пришлю пуллреквест на неделе. Вопрос, как тестировать новый дизайн мне тоже интересен. С внешними страницами всё понятно, а вот как посмотреть и потестировать те, которые доступны только после авторизации? У вас есть тестовая площадка?
Наверное, я бы мог поднять песочницу у себя на сервере, если для этого хватит только лишь LAMP-стека, но инструкция бы не помешала.

0. Про цвета - понял. Сначала разберусь с расположением, потом поправим цвета.
1. Да, понял, придётся логику переделать довольно сильно. Но на всякий случай отмечу, что в текущей версии на mmb.progressor.net я Значков через Файлы не вижу.
2. Пояснение к поиску в колонке меню - это просто недоделка, исправлю. На мой взгляд все формы поиска выполнены странно и постараюсь подумать, как это улучшить.

**Comment by leonidfishkis** [comment]
@santiago26   по технологии - понятно. 

>У вас есть тестовая площадка?
да,  есть тестовая база и каталог, в котором тестируются скрипты. Я так понимаю, что нам нужно на сервер установить файлы фреймворка, а в этот github  Вы будете загружать только  файл стилей? 

> которые доступны только после авторизации
а кто мешает авторизоваться? Вы не зарегистрированы на сайте?

>на всякий случай отмечу
Ну за progressor.net я ничего сказать не могу, а вот на .ru, скорее всего, Вы смотрите текущий  ММБ, а в нём ещё значок не загружен - поменяйте на  2014  осень или весна и посмотрите раздел Файлы.

**Comment by santiago26** [comment]
Я зарегистрирован на сайте, но вот емэйл не помню. Регистрировать нового пользователя не хочу, чтобы не плодить энтропию.

**Comment by santiago26** [comment]
http://mmb.progressor.ru/php/mmbscripts_design/index.php
Отзывы по текущему виду были бы полезны (что изменить). Я собираюсь продолжать работу над меню с тем, чтобы там появилось три раздела: ММБ, Пользователи, Команды.
Предполагаю как-то так:
![default](https://cloud.githubusercontent.com/assets/1297578/6893077/89263b94-d6d2-11e4-8b5d-78661772bb86.png)

**Comment by leonidfishkis** [comment]
@santiago26  Напишите мне на почту  имя и фамилию - я посмотрю, что в базе и поставлю актуальный email
Мой адрес: имя прользователя, как здесь на сервере gmail.com

**Comment by leonidfishkis** [comment]
> Предполагаю как-то так:

Пользователи и рейтинг с текущим ММБ не связаны, поэтому на мой взгляд, нужно убрать рейтинг из раздела "Выбранный ММБ"  
Под "администрирование" попадают практически все объекты (команды, точки, файлы, параметры ММБ), поэтому я бы этот термин не использовал.
У Адимнистратора сервиса часть дополнительных опций становится доступна без изменения визкального стиля (например, он может редактировать команду или получать расширенный вывод пользователей по поиску), а часть с изменением (например, дополнительные пункты меню)
"Обычный" пользователь не увидит (не должен увидеть) ссылку "Новый ММБ", поэтому может и стиль для администратора  потребуется делать отдельно...

**Comment by santiago26** [comment]
Спасибо за помощь в индивидуальном порядке, но, надеюсь, когда-нибудь сообщество ММБ разберётся и с этой проблемой. Мне известны случаи, когда люди заводили аккаунты-дубликаты. Кажется, что для решения этой проблемы, можно было бы высылать пользователям приветственное письмо при регистрации.

**Comment by santiago26** [comment]
Отличная идея отдельного стиля для администратора! Покрашу все административные функции в красный цвет. Пока что только несколько функций, которые нашёл, а остальные по мере обнаружения.
Блок "Администрирование", который на скриншоте выше, действительно не выводится для обычных пользователей. Они сразу видят "Выбранный ММБ" под годом.

**Comment by leonidfishkis** [comment]
@santiago26  можно было бы высылать пользователям приветственное письмо при регистрации.

Это и так делается - просто нужно понимать, что сайт в нынешнем виде работает с 2012 года, а по участникам ММБ до этого времени не удалось перенести базу с emailами, поэтому была проделана большая работа по импорту данных и, в частности,   создание учётных записей без реальных адресов. Об этом писалось в сообществе, но периодически такие люди находятся :) 
Их немного, так что проблема решается в ручном режиме по запросу на общий адрес.
Если человек регистрировался, а потом не может вспомнить или потеряд доступ - он пишет на общий адрес. Таких случаев за всё время меньше десяти.
