### ISSUE TITLE
Переработка раздела Файлы

### ISSUE THREAD

**Issue by santiago26** [realtim/mmb#97]
Во время обсуждения #95 столкнулись с вопросами, которые требуют отдельного обсуждения перед тем, как что-либо делать.

> Значки теперь доступны через Файлы, и я не уверен, что вообще нужна отдельная ссылка на статическую страницу.

Вопрос  1. Может быть стоит сохранить раздел значков? 
Мне кажется, что ссылка в разделе "Файлы" выглядит хуже, чем картинка в разделе "Значки". 
Надо ответить на вопрос: хорошо ли, когда можно посмотреть и сравнить все значки ММБ за многие годы? Мне кажется, что да, поэтому я считаю, что раздел "Значки" нужен. Как компромисс, сохранить текущий вариант: и в файлах их держать, и в отдельном разделе.

Вопрос  2. Сейчас раздел "Файлы" сам по себе — странная вещь. Это больше похоже на сборную солянку, помойку, нежели на удобный способ что-либо найти. Известный факт из области юзабилити: любой список должен содержать 5±2 элемента. 
С другой стороны, если превратить раздел "Файлы" во что-то большее, чем табличка, то это может быть удобно. Но возможности сравнивать значки всё равно не даст.

В моём представлении раздел должен называться "Материалы" и выглядить примерно так:
![files](https://cloud.githubusercontent.com/assets/1297578/6881034/d8666ece-d55e-11e4-90b7-2245b95289b9.png)

**Comment by leonidfishkis** [comment]
>Это больше похоже на сборную солянку, помойку, нежели на удобный способ что-либо найти
Во-первых, это уже структурированная помойка, а во-вторых, важно с какой стороны смотреть.
Сайт - это прежде всего инструмент для организации марш-броска, то есть Саша Тонис или другой администратор сервиса должен иметь возможность без участия разработчиков быстро загрузить файлы, описать марш-бросок  и получить на выходе  работающую ситсему регистрации, в которой пользователи видят необходимоую информацию.
Я не против изменения внешнего вида этого раздела, если это не помешает основной задаче.
Может быть, нужно сделать изменение стиля только для "обычных" пользователей, а администраторам оставить старый режим.

По значкам. Конечно, можно оставить пункт "Значки" - просто страница должна стать не статичной, а  генерироваться  по ссылкам из базы и быть вписаной в общую логику, как Команды, Файлы и т.п.

**Comment by santiago26** [comment]
Административный интерфейс я пока так и не видел, так что по его поводу ничего и не предлагаю, на макете про него ничего нет. Можно сделать изменение только для пользователей, согласен, но если получится упростить жизнь и администраторам, то почему бы и нет.

Проблема страницы "Значков" в статичности, значит. Понял.

А правильно ли я понял, что работа администратора по созданию нового ММБ стооится в основном вокруг раздела Файлы?
Или что это является некоторой целью на перспективу.
