### ISSUE TITLE
Ссылка на объявление о ММБ-2103-осень ведет в ЖЖ

### ISSUE THREAD

**Issue by Pavel-Y** [realtim/mmb#99]
В списке дистанций ссылка от слова Арсаки (2013 осень) ведет в ЖЖ http://community.livejournal.com/_mmb_/262946.html
в то время как со всех остальных случаях в этом же столбце - на сайт ММБ, например http://mmb.progressor.ru/mmbfiles/mmb2008o-.htm

**Comment by leonidfishkis** [comment]
Исправлено
